config:
  gcp:project: peerless-window-480013-t4
  gcp:region: us-central1
  server:cloudSqlConnectionName: peerless-window-480013-t4:us-central1:marmalade-db
  server:databaseUrl:
    secure: AAABAJNPlQ2DRLIruegDjiCo1mw24C/b8I5Cl/N4/C7TNqoK42uF+gpqIiz6uJIO0zhMrHgjFzEgu85ofy3zIH+oB3xR9TFsNoR4wHItQHZYaeDopi3EPYiTEHysJvXE5DaQi4+IxWI=
  server:jwtSecret:
    secure: AAABANdNqRWiYCs+yFllUAvZ2gice4zXYtw19SHM/Ct8F3Hc1aZqbgDJ3C+a6c1Si93sdV4mRy4=
  server:jwtPublicKey:
    secure: AAABAPDtTyH1QWUyG7RpJL8VyuT8La+DXp2QOxLN/BU1
  server:googleClientId:
    secure: AAABANaJS77h1S8Vdyx2RvxcwKy2qyezYU9uvNxhO83Ju2vHy8XOXmYxI8KEpVTIOqzNdYeWfQTSK7AjdkeOdnnt0CIukDn8PtJVv+OaRgUDotQy8k4ps5171W1SDSFtfYkM0T49j60=
  server:googleClientSecret:
    secure: AAABAPtsg6X87HcrmVZmEzBbhIaAzqzlptYfLG50YmILUsXEjx/WmFedVrYmBQ5Q95VZePiUSV81xfBty2bvMoh53w==
  server:elevenlabsWebhookSecret:
    secure: AAABALUmIA8Gu9n9m7FKuMbiOr4iPs87eN/Eabb1wLkKUMWck9pXXgAQepkdDKtCOeHvXjM9wrkB6kRmUyQwZcZ6yY4uzpz1ERAD0SsxKuWiEgPQyWfi9YnF+AYcBae1Dqz3wPSYRht/G9oB/amcOgstwEsawXtiRY0xHlsv8BG8LwOaXBlixcnJdvNyAV7Ty/o2ULsdgT1Ym0+VXA4mrX7THTST+YjF9nxGgb2QCBG1KdYKkuPOPmsV4vRNjmZOCsf38PdGoVXaOvr6Y2luj6XtG0vovA2K99pOIdsfHE+QHgy5CXisC1oqgSiDEGPyZaRov/Y+oPGebfLzMHdowkXrBoxyRp7exbIXtwk4dLx8oYvqYrIpVaH97jpHKnDYiK6S4nWDKQasnwLqy2OLWUle4BDv1HTtGndN5i2Vy/sVmKWsBse1fJ2U24FcYjkFSAhhI88lvOvGGqUBUkVtZ/sxSDbT4qDYHWe3A7aQLKTCIAP5qsiVz6q2pwfB1K5zTQxa9lI9CaGXoMLg0hZ59SXNMU59VuJgSibkRjyoxUmkGl34pxLgGpf3ZBwiXRWky59Y8mpxe0LluinH9U201Kz6L34wEBMmXkHrLH9pKr/Wjgr1L1VK4H+63x0Mu59mOgdzZXyyIzOdAiLL8SPzNt/MhH+MxWfIqpQfqq2X0b2cL9WIPlggQ3BD7/MCYE4mUbWSFd2/2laIniCTR3QFMmfTXe2tUnd375pEOHm0ddxIUFlfBeUc8FqWSpsHYa4VGJACeq+RwGog9h2o/o42B5zUDfunTCYCU8FXN5wehfizYEDx5qXfVOX7gDeIHo/ok69xXfIa/lqaH2wXTHJLHHT9WrTGDlUSHH7FVVwPE56co9YDhTl2nOTkUxxbkh+3uBuiipROU7ZGY9OvgZOa2pXi/mZ+nrSeSqtqgYtGGDHQEAmnhwbFdmKmqAAoGq+R4glFyOshDNUNbTLvijb+W7Gd7Y7lkXQ6+nApsKxkyoIHVektfHJiHCnPwudICKMDvRkvj5K+fZlR9Vf7zzk5HEIY5ZDXZ7cQxXNl1RIoQgdx86sEi8jXl8NbGk0PsEFUJ1sGm9tmAWxPY3EELUw6nVrV8oxeVwTtBhnasg==
  server:elevenlabsDefaultUserId:
    secure: AAABANO2KDj01KfL8cpMC0vrglkwZcp3VsL6BtzEi9psf5YALqRjTx/kmA3arkammxLQOIf4vYKj9Cgd41Jalw==
